databases:
  - name: sawaaba-psql
    plan: free
    databaseName: sawaaba_db
    user: sawaabadbuser1

services:
  - type: web
    plan: free
    name: sawaaba-travel-celery
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn SAWAABA_CELERY.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sawaaba-psql
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4